name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04  # Updated from ubuntu-20.04 to avoid deprecation issues

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Date
        id: get-date
        run: echo "date=$(date -u "+%Y%m%d")" >> "$GITHUB_ENV"
        shell: bash

      - name: Cache Buildozer Global Directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer Directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk  # Ensure this matches the output directory of Buildozer
