name: Build APK with Buildozer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 45  # Increased timeout for NDK/SDK downloads

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip \
            openjdk-17-jdk autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            cython3

      - name: Install Python dependencies
        run: |
          pip install buildozer cython==0.29.33

      - name: Setup Android environment
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # Initialize Buildozer if needed
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Install Android SDK and NDK
        run: |
          # Clean previous installations
          rm -rf ~/.buildozer/android/platform
          mkdir -p ~/.buildozer/android/platform
          
          # Install Command Line Tools
          cd ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mkdir -p cmdline-tools
          mv cmdline-tools cmdline-tools/latest
          
          # Set environment variables
          export ANDROID_SDK_ROOT=~/.buildozer/android/platform
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          
          # Accept licenses first
          yes | sdkmanager --licenses
          
          # Install platform tools and build tools
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          
          # Verify installation
          ls -la $ANDROID_SDK_ROOT/build-tools/34.0.0/aidl

      - name: Build APK
        run: |
          export JAVA_OPTS="-Xmx4G"  # Increased memory
          export ANDROID_SDK_ROOT=~/.buildozer/android/platform
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
