name: Build APK with Buildozer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip \
            openjdk-17-jdk autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            cython3

      - name: Install Python dependencies
        run: |
          pip install buildozer cython==0.29.33

      - name: Setup Android SDK/NDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # Clean previous installations
          rm -rf ~/.buildozer/android
          mkdir -p ~/.buildozer/android/platform

          # Install Command Line Tools with correct structure
          cd ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest

          # Create compatibility symlink
          ln -s cmdline-tools/latest android-sdk/tools

      - name: Install Android components
        run: |
          export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Force NDK installation
        run: |
          buildozer android update  # Triggers NDK download
          ls -la ~/.buildozer/android/platform/android-ndk*

      - name: Build APK
        run: |
          export JAVA_OPTS="-Xmx4G"
          export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
          export ANDROID_NDK_HOME=~/.buildozer/android/platform/android-ndk-r25b
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
