name: Android APK Builder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip python3-venv \
            openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev cython3

      - name: Setup Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install buildozer cython==0.29.33

      - name: Install Android SDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          
          # Download official Android tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          
          # Create proper directory structure
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest
          
          # Setup environment
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          
          # Accept licenses and install components
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Install Android NDK
        run: |
          cd ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-*.zip
          rm android-ndk-*.zip

      - name: Configure buildozer
        run: |
          source venv/bin/activate
          echo "[buildozer]
          android.sdk_path = $HOME/.buildozer/android/platform/android-sdk
          android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b
          android.skip_clean = True" >> buildozer.spec

      - name: Verify installations
        run: |
          ls -la ~/.buildozer/android/platform/android-sdk/build-tools/34.0.0/aidl
          ls -la ~/.buildozer/android/platform/android-ndk-r25b

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
