name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip \
            openjdk-17-jdk autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            cython3

      - name: Install Python dependencies
        run: |
          pip install buildozer cython==0.29.33

      - name: Initialize Buildozer environment
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          echo "Initializing Buildozer..."
          buildozer init  # Initialize without full build
          echo "Downloading Android SDK..."
          buildozer android update sdk --no-use-sdk-wrapper --accept-licenses

      - name: Install specific build-tools
        run: |
          echo "Installing build-tools..."
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "build-tools;34.0.0" \
            "platforms;android-34" \
            "platform-tools" \
            "cmdline-tools;latest"

      - name: Verify Android tools
        run: |
          echo "Android SDK contents:"
          ls -la ~/.buildozer/android/platform/android-sdk
          echo "Build tools contents:"
          ls -la ~/.buildozer/android/platform/android-sdk/build-tools/34.0.0/
          ~/.buildozer/android/platform/android-sdk/build-tools/34.0.0/aidl --version

      - name: Build APK
        run: |
          export JAVA_OPTS="-Xmx2G"
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
