name: Build APK with Buildozer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip \
            openjdk-17-jdk autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            cython3

      - name: Install Python dependencies
        run: |
          pip install buildozer cython==0.29.33

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # Initialize Buildozer environment
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          
          # Clean previous installations
          rm -rf ~/.buildozer/android/platform/android-sdk
          
          # Install Command Line Tools
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mv cmdline-tools latest
          cd -

      - name: Install Android components
        run: |
          export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          
          # Verify installation
          ls -la $ANDROID_SDK_ROOT/build-tools/34.0.0/aidl

      - name: Build APK
        run: |
          export JAVA_OPTS="-Xmx2G"
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
