name: Android APK Builder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Nuclear cleanup
        run: |
          rm -rf ~/.buildozer ~/.android ~/.gradle venv
          rm -f buildozer.spec

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip python3-venv \
            openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev cython3

      - name: Setup fresh environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install buildozer cython==0.29.33
          buildozer init

      - name: Create clean buildozer.spec
        run: |
          cat << EOF > buildozer.spec
          [app]
          title = MyApp
          package.name = myapp
          package.domain = org.example
          source.dir = .
          source.include_exts = py,png,jpg,kv,ttf,json
          version = 1.0
          requirements = python3,kivy,openssl,sqlite3,android
          orientation = portrait
          osx.python_version = 3

          [buildozer]
          log_level = 2
          android.skip_clean = True
          android.accept_sdk_license = True
          android.sdk_path = /home/runner/.buildozer/android/platform/android-sdk
          android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk-r25b
          EOF

      - name: Install Android SDK/NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          
          # Install SDK
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest
          
          # Install components
          yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

          # Install NDK
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-*.zip
          rm android-ndk-*.zip

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
