name: Build APK with Buildozer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip \
            openjdk-17-jdk autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            cython3

      - name: Install Python dependencies
        run: |
          pip install buildozer cython==0.29.33

      - name: Setup Android environment
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # Only initialize if spec file doesn't exist
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          
          # Update Android SDK components
          buildozer android update

      - name: Install Android SDK components
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          
          # Wait for SDK manager
          while [ ! -f $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager ]; do
            sleep 5
          done
          
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Verify aidl exists
        run: |
          ls -la $HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0/aidl

      - name: Build APK
        run: |
          export JAVA_OPTS="-Xmx2G"
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
