name: Android APK Builder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean environment
        run: |
          rm -rf ~/.buildozer ~/.android ~/.gradle venv
          rm -f buildozer.spec

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip python3-venv \
            openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev cython3

      - name: Setup Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install buildozer cython==0.29.33

      - name: Create buildozer.spec
        run: |
          cat << EOF > buildozer.spec
          [app]
          title = MyApp
          package.name = myapp
          package.domain = org.example
          source.dir = .
          source.include_exts = py,png,jpg,kv,ttf,json
          version = 1.0
          requirements = python3,kivy,openssl,sqlite3,android
          orientation = portrait

          [buildozer]
          log_level = 2
          android.skip_clean = True
          android.accept_sdk_license = True
          android.sdk_path = $HOME/.buildozer/android/platform/android-sdk
          android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b
          EOF

      - name: Install Android SDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          
          # Install command line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -qq commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          
          # Create proper directory structure
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest
          
          # Create legacy symlinks
          ln -sfn cmdline-tools/latest android-sdk/tools
          ln -sfn ../cmdline-tools/latest/bin android-sdk/tools/bin

      - name: Install Android components
        run: |
          export ANDROID_SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
          export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin"
          
          # First install platform-tools to get basic components
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
          
          # Then install build-tools
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0"
          
          # Finally install platform
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-34"
          
          # Accept licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android NDK
        run: |
          cd ~/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -qq android-ndk-*.zip
          rm android-ndk-*.zip

      - name: Verify installations
        run: |
          ls -la $HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0/aidl
          ls -la $HOME/.buildozer/android/platform/android-ndk-r25b

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
