name: Bulletproof APK Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Purge previous installations
        run: |
          rm -rf ~/.buildozer
          rm -rf ~/.android
          rm -rf ~/.gradle

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git zip unzip python3-pip python3-venv \
            openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev cython3 \
            libssl-dev libffi-dev

      - name: Setup Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel
          pip install buildozer cython==0.29.33

      - name: Manual Android SDK/NDK install
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform

          # Install Command Line Tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -qq commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest

          # Install NDK
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -qq android-ndk-*.zip
          rm android-ndk-*.zip
          mv android-ndk-r25b android-ndk-r25b

          # Create legacy symlinks
          ln -s cmdline-tools/latest android-sdk/tools
          ln -s cmdline-tools/latest/bin/sdkmanager android-sdk/tools/bin/sdkmanager

      - name: Configure Android environment
        run: |
          echo "ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=~/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_ENV

          # Accept licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

          # Install essential components
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Build with verbose logging
        run: |
          source venv/bin/activate
          buildozer android clean
          buildozer -v android debug 2>&1 | tee build.log
          [ -f bin/*.apk ] || (echo "APK not found!" && exit 1)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
