name: Android APK Builder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean environment
        run: |
          # Preserve python-for-android directory
          rm -rf ~/.buildozer/android/{platform,app,deps}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip python3-venv \
            openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev cython3

      - name: Setup Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel
          pip install buildozer cython==0.29.33

      - name: Initialize Buildozer
        run: |
          source venv/bin/activate
          buildozer init
          buildozer android update  # Initialize p4a

      - name: Install Android SDK/NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          
          # Install SDK
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -qq commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest
          ln -sfn cmdline-tools/latest android-sdk/tools

          # Install NDK
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -qq android-ndk-*.zip
          rm android-ndk-*.zip

          # Verify p4a exists
          ls -la ../python-for-android

      - name: Configure environment
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_ENV

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
